name: Pocket Poster

options:
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.leminlimez.pocketposter
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: "1"   # ← iPhone のみ
    CODE_SIGNING_ALLOWED: NO
    ENABLE_BITCODE: NO

targets:
  Pocket Poster:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Pocket Poster
    settings:
      base:
        PRODUCT_NAME: Pocket Poster
        INFOPLIST_FILE: Pocket Poster/Info.plist
    attributes:
      SupportsMacCatalyst: false
      SupportsDesignedForiPad: false