name: Pocket Poster

options:
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  Pocket Poster:
    type: application
    platform: iOS

    sources:
      - path: Pocket Poster

    resources:
      - path: Pocket Poster
        includes:
          - "**/*.xcassets"
          - "**/*.strings"
          - "**/*.stringsdict"
          - "**/*.xcstrings"

    info:
      path: Pocket Poster/Info.plist

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lemin.Pocket-Poster
        MARKETING_VERSION: "3.0"
        CURRENT_PROJECT_VERSION: "0"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

schemes:
  Pocket Poster:
    archive:
      config: Release