name: Pocket Poster

options:
  bundleIdPrefix: ""
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  developmentLanguage: ja

settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_STYLE: Manual
    ENABLE_BITCODE: NO
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: Pocket-Poster-Info.plist
    PRODUCT_NAME: Pocket Poster

targets:
  Pocket Poster:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    scheme:
      testTargets: []
      gatherCoverageData: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.leminlimez.pocketposter
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
    sources:
      - path: Pocket Poster
        excludes:
          - Preview Content
    resources:
      - path: Pocket Poster/Assets.xcassets
      - path: Pocket Poster/Preview Content/Preview Assets.xcassets
      - path: Pocket Poster/Resources
      - path: Pocket Poster/Localizable.xcstrings
      - path: Pocket Poster/Pocket-Poster-InfoPlist.xcstrings
    info:
      path: Pocket-Poster-Info.plist
      properties: {}

targetTemplates: {}