name: Pocket Poster

options:
  deploymentTarget:
    iOS: "17.0"
  bundleIdPrefix: com.lemin
  developmentLanguage: ja   # 日本語

settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

    # コードサイン無し
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""

    # Xcode 16 系で安全な設定
    GENERATE_INFOPLIST_FILE: YES
    ENABLE_BITCODE: NO
    SWIFT_TREAT_WARNINGS_AS_ERRORS: NO
    OTHER_SWIFT_FLAGS: ""

    # リリース最適化
    SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    SWIFT_COMPILATION_MODE: "wholemodule"
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    ENABLE_TESTABILITY: NO

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19
  Dynamic:
    url: https://github.com/mhdhejazi/Dynamic.git
    from: 1.2.0
  SwiftUICachedAsyncImage:
    url: https://github.com/lorenzofiamingo/swiftui-cached-async-image.git
    from: 2.1.1

targets:
  Pocket Poster:
    type: application
    platform: iOS

    sources:
      - path: Pocket Poster

    resources:
      - path: Pocket Poster/Assets.xcassets
      - path: Pocket Poster/Preview Content

    dependencies:
      - package: ZIPFoundation
      - package: Dynamic
      - package: SwiftUICachedAsyncImage

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lemin.Pocket-Poster
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_TREAT_WARNINGS_AS_ERRORS: NO