name: Pocket Poster

options:
  xcodeVersion: "26.0"
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    TARGETED_DEVICE_FAMILY: "1,2"
    PRODUCT_NAME: "Pocket Poster"

targets:
  Pocket Poster:
    type: application
    platform: iOS

    sources:
      - path: Pocket Poster
        excludes:
          - "**/*.xcassets"
          - "**/*.lproj"
          - "Preview Content"

    resources:
      - path: Pocket Poster/Assets.xcassets
      - path: Pocket Poster/Preview Content
      - path: Pocket Poster
        includes:
          - "**/*.lproj"

    info:
      path: Pocket Poster/Info.plist

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lemin.Pocket-Poster
        DEVELOPMENT_TEAM: 2P4CP47H76
        MARKETING_VERSION: "3.0"
        CURRENT_PROJECT_VERSION: "0"
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

schemes:
  Pocket Poster:
    archive:
      config: Release