name: PocketPoster
options:
  bundleIdPrefix: com.lemin
  deploymentTarget:
    iOS: '16.0'
  generateHeaderSymlinks: false
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    CODE_SIGN_STYLE: Manual        # 署名なし
    CODE_SIGNING_REQUIRED: NO      # ビルド時に署名不要
    MARKETING_VERSION: 3.0
    CURRENT_PROJECT_VERSION: 0
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    SWIFT_EMIT_LOC_STRINGS: YES
    ONLY_ACTIVE_ARCH: YES
    GCC_OPTIMIZATION_LEVEL: 0
    DEBUG_INFORMATION_FORMAT: dwarf
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"

targets:
  PocketPoster:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    productName: PocketPoster
    info:
      path: Pocket-Poster-Info.plist
    sources:
  - "./Pocket Poster/**"
　　resources:
  - "./Pocket Poster/**"
    dependencies:
      - package: ZIPFoundation
      - package: Dynamic
      - package: swiftui-cached-async-image

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    from: 0.9.19
  Dynamic:
    url: https://github.com/mhdhejazi/Dynamic
    from: 1.2.0
  swiftui-cached-async-image:
    url: https://github.com/lorenzofiamingo/swiftui-cached-async-image
    from: 2.1.1
